package network.protocol;

public enum MessageType {
    CONNECT_REQUEST,
    CONNECT_RESPONSE,
    PLAYER_JOINED,
    PLAYER_LEFT,
    ERROR,
    LOBBY_STATE,
    SET_READY_REQUEST,
    START_GAME_REQUEST,
    GAME_STARTED,
    END_TURN_REQUEST,
    TURN_CHANGED,
    CHAT_MESSAGE,
    DECLARE_WAR_REQUEST,
    DIPLOMACY_CHANGED,
    SELECT_MAP_REQUEST,
    GAME_STATE_SNAPSHOT,
    MOVE_UNIT_REQUEST,
    UNIT_MOVED
}
